upstreams:
  groups:
    default:
      - https://dns.nextdns.io/ca7d51/av
ports:
  dns: 53
  http: 4000
prometheus:
  enable: true
  path: /metrics
bootstrapDns:
  - 1.1.1.1
blocking:
  denylists:
    ads:
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/pro.txt
  clientGroupsBlock:
    default:
      - ads
caching:
  minTime: 5m
  maxTime: 30m
  prefetching: true
