upstreams:
  groups:
    default:
      - 1.1.1.1
      - 8.8.8.8
ports:
  dns: 0.0.0.0:53
  http: 0.0.0.0:4000
bootstrapDns:
  - 1.1.1.1
blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - ads
caching:
  minTime: 5m
  maxTime: 30m